# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 30


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Docker build
        run: |
          docker image build -t nginx-portfolio-image .
      - name: Docker push
  #docker login -u thomasmauran -p ${{ secrets.DOCKER_TOKEN }}
       #   docker run -h thomasprojects.works thomasmauran/dockerfile 

        run: |
          docker stop nginx-portfolio
          docker rm nginx-portfolio
          docker container run --name nginx-portfolio -p 80:80 -p 443:443 -d nginx-portfolio-image
          docker start nginx-portfolio
          
